---
- name: Get latest stern_version of stern
  ansible.builtin.shell: curl -Is https://github.com/stern/stern/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: stern_version
  changed_when: false

- name: "Latest stern_version of stern:"
  ansible.builtin.debug:
    var: stern_version.stdout

- name: "Set fact with latest stern_version of stern"
  ansible.builtin.set_fact:
    stern_version: "{{ stern_version.stdout }}"
