---
- name: Get installed stern_version
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: stern -v | grep -i stern_version | awk '{print $2}'
  register: stern_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed stern_version of stern:"
  ansible.builtin.debug:
    var: stern_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: stern_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: stern_installed_version.stdout != stern_version
