---
# /usr/share/applications/sublime_text.desktop
# https://github.com/keeweb/keeweb/releases/download/v1.6.3/KeeWeb-1.6.3.linux.x64.zip

- name: Get installed version
  ansible.builtin.shell: cat /opt/keeweb/version.tag
  register: keeweb_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed version of keeweb:"
  ansible.builtin.debug:
    var: keeweb_installed_version.stdout

- name: Directory for KeeWeb
  ansible.builtin.file:
    path: /opt/keeweb
    state: directory
    mode: "0755"

- name: Get latest version
  ansible.builtin.shell: curl -Is "https://github.com/keeweb/keeweb/releases/latest" | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: keeweb_version_tag
  changed_when: keeweb_version_tag.stdout != keeweb_installed_version.stdout

- name: "Latest version of keeweb:"
  ansible.builtin.debug:
    var: keeweb_version_tag.stdout

- name: Download .zip
  ansible.builtin.get_url:
    url: "https://github.com/keeweb/keeweb/releases/download/v{{ keeweb_version_tag.stdout }}/KeeWeb-{{ keeweb_version_tag.stdout }}.linux.x64.zip"
    dest: /tmp/keeweb.zip
    mode: "0644"
  when: keeweb_installed_version.stdout != keeweb_version_tag.stdout

- name: Remove old KeeWeb
  ansible.builtin.file:
    path: /opt/keeweb/*
    state: absent
  when: keeweb_installed_version.stdout != keeweb_version_tag.stdout

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/keeweb.zip
    dest: /opt/keeweb/
    remote_src: true
  when: keeweb_installed_version.stdout != keeweb_version_tag.stdout

- name: Add gnome icon
  ansible.builtin.copy:
    src: keeweb.desktop
    dest: /usr/share/applications/keeweb.desktop
    mode: "0644"

- name: Add version file
  ansible.builtin.shell: echo '{{ keeweb_version_tag.stdout }}' > /opt/keeweb/version.tag
  when: keeweb_installed_version.stdout != keeweb_version_tag.stdout
