---
- name: Stop container using docker-compose
  ansible.builtin.command: docker-compose stop
  changed_when: adguard_home_up_result.stderr_lines | length > 1
  register: adguard_home_up_result
  args:
    chdir: "{{ adguard_home_install_path }}"

- name: Remove all volumes/containers using docker-compose
  ansible.builtin.command: docker-compose rm -vf
  args:
    chdir: "{{ adguard_home_install_path }}"

- name: Ensure adguard_home_install_path dir is removed
  ansible.builtin.file:
    path: "{{ adguard_home_install_path }}"
    state: absent
