---
- name: Ensure install dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ adguard_home_install_path }}"
    - "{{ adguard_home_install_path }}/confdir"
    - "{{ adguard_home_install_path }}/workdir"

- name: Configure docker-compose file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ adguard_home_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  loop:
    - docker-compose.yaml

- name: Configure confdir/AdGuardHome.yaml file
  ansible.builtin.template:
    src: "{{ adguard_home_templates_path }}/{{ item }}"
    dest: "{{ adguard_home_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  loop:
    - confdir/AdGuardHome.yaml

# - ansible.builtin.import_tasks: config.yaml

- name: Pull Docker image using docker-compose
  ansible.builtin.command: docker-compose pull
  changed_when: adguard_home_pull_result.stderr_lines | length > 2
  register: adguard_home_pull_result
  args:
    chdir: "{{ adguard_home_install_path }}"

- name: Run using docker-compose
  ansible.builtin.command: docker-compose up -d
  changed_when: adguard_home_up_result.stderr_lines | length > 2
  register: adguard_home_up_result
  args:
    chdir: "{{ adguard_home_install_path }}"

# - name: Restart using docker-compose
#   ansible.builtin.command: docker-compose restart
#   args:
#     chdir: "{{ adguard_home_install_path }}"
