---
- name: Check docker-compose executable is present
  ansible.builtin.shell: "which docker-compose"
  register: adguard_home_docker_compose_result
  ignore_errors: true
  changed_when: false

- name: Fail on condition
  ansible.builtin.fail:
    msg: "docker-compose is not found! You need to install it first."
  when: adguard_home_docker_compose_result.rc != 0

- name: Ensure passlib is installed
  delegate_to: localhost
  ansible.builtin.pip:
    name:
      - passlib
    state: present

- name: Include cleanup.yaml
  ansible.builtin.include_tasks: cleanup.yaml
  when: adguard_home_clean

- name: Import install.yaml
  ansible.builtin.import_tasks: install.yaml

- name: Import adguard_home_dhcp.yaml
  ansible.builtin.import_tasks: adguard_home_dhcp.yaml
