---
letsencrypt_coredns_account_path: "/etc/ssl/le/account"
letsencrypt_coredns_account_key_path: "{{ letsencrypt_coredns_account_path }}/account.key"

letsencrypt_coredns_certs_path: "/etc/ssl/le/certs"
letsencrypt_coredns_cert_path: "{{ letsencrypt_coredns_certs_path }}/{{ cert.cn }}"
letsencrypt_coredns_cert_key_path: "{{ letsencrypt_coredns_cert_path }}/cert.key"
letsencrypt_coredns_cert_csr_path: "{{ letsencrypt_coredns_cert_path }}/cert.csr"
letsencrypt_coredns_cert_crt_path: "{{ letsencrypt_coredns_cert_path }}/cert.crt"
letsencrypt_coredns_cert_pfx_path: "{{ letsencrypt_coredns_cert_path }}/cert.pfx"
letsencrypt_coredns_cert_fullchain_path: "{{ letsencrypt_coredns_cert_path }}/cert.fullchain"
letsencrypt_coredns_cert_chain_path: "{{ letsencrypt_coredns_cert_path }}/cert.chain"

# letsencrypt_api: "https://acme-v02.api.letsencrypt.org/directory"
letsencrypt_coredns_letsencrypt_api: "https://acme-staging-v02.api.letsencrypt.org/directory"
letsencrypt_coredns_letsencrypt_api_version: 2
letsencrypt_coredns_letsencrypt_email: "test@mail.com"
letsencrypt_coredns_letsencrypt_days: 30

letsencrypt_coredns_key_size: "4096"
letsencrypt_coredns_force_cert_creation: "false"

letsencrypt_coredns_certs:
  - cn: "example.com"
    domain_name: "example.com"
    sans:
      - "www.example.com"
      - "dns.example.com"
