---
- name: Restart zabbix-agent2
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
  become: true

- name: Restart zabbix-agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
  become: true
