---
- name: Ensure install dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ coredhcp_install_path }}"
    - "{{ coredhcp_install_path }}/config"

- name: Configure docker-compose file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ coredhcp_install_path }}/{{ item }}"
    mode: "0664"
  loop:
    - docker-compose.yaml
    - config/config.yaml
    - config/file_leases.txt

- name: Import config.yaml
  ansible.builtin.import_tasks: config.yaml

- name: Pull Docker image using docker-compose
  ansible.builtin.command: docker-compose pull
  changed_when: coredhcp_pull_result.stderr_lines | length > 2
  register: coredhcp_pull_result
  args:
    chdir: "{{ coredhcp_install_path }}"

- name: Run using docker-compose
  ansible.builtin.command: docker-compose up -d
  changed_when: coredhcp_up_result.stderr_lines | length > 2
  register: coredhcp_up_result
  args:
    chdir: "{{ coredhcp_install_path }}"
