---
- name: "[BREW] Add third-party taps"
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_trust_taps }}"
  become: false
  when: brew_trust_taps | length > 0

- name: "[BREW] Trust third-party taps"
  ansible.builtin.command: "{{ brew_install_path }}/bin/brew trust {{ item }}"
  loop: "{{ brew_trust_taps }}"
  changed_when: true
  become: false
  when: brew_trust_taps | length > 0

- name: "[BREW] Install formulae"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    path: "{{ brew_install_path }}/bin"
  loop: "{{ brew_pkgs }}"
  become: false

- name: "[BREW] Install casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    # path: "~/Applications"
    install_options: "appdir=~/Applications"
    accept_external_apps: true
  loop: "{{ brew_cask_pkgs }}"
  become: false
