---
- name: Import setup.yaml
  ansible.builtin.import_tasks: setup.yaml

- name: Import install.yaml
  ansible.builtin.import_tasks: install.yaml

- name: Import update.yaml
  ansible.builtin.import_tasks: update.yaml
  tags:
    - update
