---
- name: Set vars
  ansible.builtin.set_fact:
    libvirt_vm_disk_path: "{{ libvirt_images_dir }}/{{ vm.name }}.qcow2"

- name: Destroy the domain with XML specification
  community.libvirt.virt:
    name: "{{ vm.name }}"
    command: destroy
  ignore_errors: true

- name: Remove storage
  ansible.builtin.file:
    path: "{{ libvirt_vm_disk_path }}"
    state: absent
