# Based on: https://github.com/DBarthe/ansible-libvirt-cloudinit
---
- name: Import setup.yaml
  ansible.builtin.import_tasks: setup.yaml

- name: Include create_vm.yaml
  ansible.builtin.include_tasks: create_vm.yaml
  loop: "{{ libvirt_vms }}"
  loop_control:
    loop_var: vm

- name: Include destroy_vm.yaml
  ansible.builtin.include_tasks: destroy_vm.yaml
  loop: "{{ libvirt_vms_to_remove }}"
  loop_control:
    loop_var: vm
