---
- name: "Create directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: qemu
    group: qemu
  loop:
    - "{{ libvirt_cloud_init_src_dir }}"
    - "{{ libvirt_cloud_init_iso_dir }}"

- name: "Download {{ libvirt_cloud_image_name }}"
  ansible.builtin.get_url:
    url: "{{ libvirt_cloud_image_url }}"
    dest: "{{ libvirt_images_dir }}/{{ libvirt_cloud_image_name }}"
    mode: "0600"
    owner: qemu
    group: qemu
    checksum: "{{ libvirt_cloud_image_checksum }}"

- name: "Install genisoimage"
  ansible.builtin.package:
    name: genisoimage
    state: present

- name: "Install pip passlib"
  ansible.builtin.pip:
    name: passlib
    state: present
