---
- name: Get latest terraform_version
  ansible.builtin.shell: curl -Is https://github.com/hashicorp/terraform/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: terraform_version
  changed_when: false

- name: "Latest terraform_version of terraform:"
  ansible.builtin.debug:
    var: terraform_version.stdout

- name: "Set fact with latest terraform_version of terraform"
  ansible.builtin.set_fact:
    terraform_version: "{{ terraform_version.stdout }}"
