---
- name: Get installed azure_functions_core_tools_version of azure_functions_core_tools
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: /opt/azure_functions_core_tools/func --version
  register: azure_functions_core_tools_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed azure_functions_core_tools_version of azure_functions_core_tools:"
  ansible.builtin.debug:
    var: azure_functions_core_tools_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: azure_functions_core_tools_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: azure_functions_core_tools_installed_version.stdout != azure_functions_core_tools_version
