---
openwrt_setup_openwrt_router_flag: false
openwrt_setup_openwrt_ap_only_flag: false
openwrt_setup_openwrt_bpir4: false

openwrt_setup_docker: false
openwrt_setup_docker_data_root: /mnt/nvme/docker
openwrt_setup_docker_nvme_device: /dev/nvme0n1p1
openwrt_setup_docker_nvme_target: /mnt/nvme
openwrt_setup_docker_nvme_fstype: ext4
openwrt_setup_docker_nvme_options: rw,noatime
openwrt_setup_docker_macvlan_name: lanmac
openwrt_setup_docker_macvlan_subnet: 192.168.1.0/24
openwrt_setup_docker_macvlan_gateway: 192.168.1.1
openwrt_setup_docker_macvlan_parent: br-lan
openwrt_setup_docker_macvlan_shim: true
openwrt_setup_docker_macvlan_shim_ifname: lanmac-shim
openwrt_setup_docker_macvlan_shim_iface: lan
openwrt_setup_docker_macvlan_shim_ip: 192.168.1.250
openwrt_setup_docker_macvlan_shim_routes:
  - 192.168.1.11
  - 192.168.1.12
