---
huawei_ip: "192.168.8.1"  # noqa: var-naming[no-role-prefix]
huawei_username: "admin"  # noqa: var-naming[no-role-prefix]
huawei_password: "admin"  # noqa: var-naming[no-role-prefix]

huawei_url: "http://{{ huawei_ip }}"  # noqa: var-naming[no-role-prefix]
huawei_lteband: "80005"  # noqa: var-naming[no-role-prefix]
