---
- name: Get latest tflint_version
  ansible.builtin.shell: curl -Is https://github.com/terraform-linters/tflint/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: tflint_version
  changed_when: false

- name: "Latest tflint_version of tflint:"
  ansible.builtin.debug:
    var: tflint_version.stdout

- name: "Set fact with latest tflint_version of tflint"
  ansible.builtin.set_fact:
    tflint_version: "{{ tflint_version.stdout }}"
