FROM ubuntu:20.04

# ENV container docker
ENV UBUNTU_USERNAME=mikee

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
      python3-pip \
    && apt-get clean all

# https://pypi.org/project/pip/
RUN pip3 install --no-cache-dir --upgrade pip==22.0.4 && \
    pip3 install --no-cache-dir \
      # https://pypi.org/project/ansible/
      ansible==5.5.0 \
      # https://pypi.org/project/yamllint/
      yamllint==1.26.3 \
      # https://pypi.org/project/packaging/
      packaging==21.3 \
      # https://pypi.org/project/pyOpenSSL/
      pyOpenSSL==22.0.0

RUN useradd ${UBUNTU_USERNAME} && usermod -aG sudo ${UBUNTU_USERNAME}

CMD ["/usr/bin/sleep", "infinity"]
