FROM ubuntu:24.04

# ENV container docker
ENV UBUNTU_USERNAME=mikee
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
      python3-pip \
      sudo \
    && apt-get clean all

# https://pypi.org/project/pip/
# rm -rfv /usr/lib/*/EXTERNALLY-MANAGED
# RUN pip3 install --break-system-packages --no-cache-dir --upgrade pip==24.3.1 && \
RUN pip3 install --break-system-packages --no-cache-dir \
      # https://pypi.org/project/ansible/
      ansible==10.5.0 \
      # https://pypi.org/project/ansible-lint/
      ansible-lint==24.9.2 \
      # https://pypi.org/project/yamllint/
      yamllint==1.35.1 \
      # https://pypi.org/project/packaging/
      packaging==24.1 \
      # https://pypi.org/project/pyOpenSSL/
      pyOpenSSL==24.2.1

RUN useradd ${UBUNTU_USERNAME} && usermod -aG sudo ${UBUNTU_USERNAME}

CMD ["/usr/bin/sleep", "infinity"]
