---
collections:
  # https://github.com/ansible-collections/community.general/releases
  - name: community.general
    version: 12.6.0
  # https://github.com/ansible-collections/community.crypto/releases
  - name: community.crypto
    version: 3.2.0
  # https://github.com/ansible-collections/community.libvirt/releases
  - name: community.libvirt
    version: 2.2.0
  # https://github.com/ansible-collections/community.zabbix/releases
  - name: community.zabbix
    version: 4.2.0
