---
- name: Include dnf.yaml
  ansible.builtin.include_tasks: dnf.yaml
  when: ansible_facts['distribution'] == "Fedora"

- name: Include apt.yaml
  ansible.builtin.include_tasks: apt.yaml
  when: ansible_facts['distribution'] == "Ubuntu"
