---
- name: Include linux.yaml
  ansible.builtin.include_tasks: linux.yaml
  when: ansible_facts['os_family'] != "Darwin"

- name: Include mac.yaml
  ansible.builtin.include_tasks: mac.yaml
  when: ansible_facts['os_family'] == "Darwin"
