---
- name: Get latest packer_version
  ansible.builtin.shell: curl -Ls https://releases.hashicorp.com/packer/ | grep packer | grep -v alpha | grep -v beta | cut -d'_' -f2 | cut -d'<' -f1 | head -n1
  register: packer_version
  changed_when: false

- name: "Latest packer_version of packer:"
  ansible.builtin.debug:
    var: packer_version.stdout

- name: "Set fact with latest packer_version of packer"
  ansible.builtin.set_fact:
    packer_version: "{{ packer_version.stdout }}"
