---
- name: Get latest istioctl_version istioctl
  ansible.builtin.shell: curl -Is https://github.com/istio/istio/releases/latest  | grep -i 'location:' | cut -f8 -d'/' | cut -d'"' -f1
  register: istioctl_version
  changed_when: false

- name: "Latest istioctl_version of istioctl:"
  ansible.builtin.debug:
    var: istioctl_version.stdout

- name: "Set fact with latest istioctl_version of istioctl"
  ansible.builtin.set_fact:
    istioctl_version: "{{ istioctl_version.stdout }}"
