---
- name: "Get installed istioctl_version of istioctl"
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: istioctl istioctl_version --remote=false | awk '{print $3}'
  register: istioctl_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed istioctl_version of istioctl:"
  ansible.builtin.debug:
    var: istioctl_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: istioctl_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: istioctl_installed_version.stdout != istioctl_version
