---
- name: Get latest kubectl_version of krew
  ansible.builtin.shell: curl -Is https://github.com/kubernetes-sigs/krew/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: kubectl_version
  changed_when: false

- name: "Latest kubectl_version of krew:"
  ansible.builtin.debug:
    var: kubectl_version.stdout

- name: "Set fact with latest kubectl_version of krew"
  ansible.builtin.set_fact:
    krew_version: "{{ kubectl_version.stdout }}"
