---
# dnf grouplist -v

- name: Import gsettings.yaml
  ansible.builtin.import_tasks: gsettings.yaml
- name: Import extensions_manual.yaml
  ansible.builtin.import_tasks: extensions_manual.yaml
# - ansible.builtin.import_tasks: extensions.yaml
# - ansible.builtin.import_tasks: remote_desktop.yaml
