---
apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: "isp-monitor"
      defaultBucket: "isp-monitor"
    secureJsonData:
      token: "isp-monitor-token"
    isDefault: true
