---
- name: Get latest trivy_version of trivy
  ansible.builtin.shell: curl -Is https://github.com/aquasecurity/trivy/releases/latest | grep -i 'location:' | cut -f3 -d'v' | cut -f1 -d'"'
  register: trivy_version
  changed_when: false

- name: "Latest trivy_version of trivy:"
  ansible.builtin.debug:
    var: trivy_version.stdout

- name: "Set fact with latest trivy_version of trivy"
  ansible.builtin.set_fact:
    trivy_version: "{{ trivy_version.stdout }}"
