---
- name: Get installed trivy_version
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: trivy version | awk '{print $3}' | cut -f2 -d'v'
  register: trivy_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed trivy_version of trivy:"
  ansible.builtin.debug:
    var: trivy_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: trivy_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: trivy_installed_version.stdout != trivy_version
