---
- name: Stop container using docker-compose
  ansible.builtin.command: docker-compose stop
  changed_when: home_assistant_up_result.stderr_lines | length > 1
  register: home_assistant_up_result
  args:
    chdir: "{{ home_assistant_install_path }}"

- name: Remove all volumes/containers using docker-compose
  ansible.builtin.command: docker-compose rm -vf
  args:
    chdir: "{{ home_assistant_install_path }}"

- name: Ensure home_assistant_install_path dir is removed
  ansible.builtin.file:
    path: "{{ home_assistant_install_path }}"
    state: absent
