---
- name: Ensure install dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ immich_install_path }}"
    # - "{{ immich_install_path }}/confdir"
    # - "{{ immich_install_path }}/workdir"

- name: Configure docker-compose file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ immich_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  loop:
    - docker-compose.yaml
    - .env

- name: Pull Docker image using docker-compose
  ansible.builtin.command: docker-compose pull
  changed_when: immich_pull_result.stderr_lines | length > 2
  register: immich_pull_result
  args:
    chdir: "{{ immich_install_path }}"

- name: Run using docker-compose
  ansible.builtin.command: docker-compose up -d
  changed_when: immich_up_result.stderr_lines | length > 2
  register: immich_up_result
  args:
    chdir: "{{ immich_install_path }}"

# - name: Restart using docker-compose
#   ansible.builtin.command: docker-compose restart
#   args:
#     chdir: "{{ immich_install_path }}"
