---
- name: Get latest version  # noqa: var-naming[no-role-prefix]
  ansible.builtin.shell: curl -Is https://github.com/zed-industries/zed/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: version
  changed_when: false

- name: "Latest version of zed:"
  ansible.builtin.debug:
    var: version.stdout

- name: "Set fact with latest version of zed"
  ansible.builtin.set_fact:
    zed_version: "{{ version.stdout }}"
