---
- name: Get latest ctop_version
  ansible.builtin.shell: curl -Is https://github.com/bcicen/ctop/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -f1 -d'"'
  register: ctop_version
  changed_when: false

- name: "Latest ctop_version of ctop:"
  ansible.builtin.debug:
    var: ctop_version.stdout

- name: "Set fact with latest ctop_version of ctop"
  ansible.builtin.set_fact:
    ctop_version: "{{ ctop_version.stdout }}"
