---
- name: Get installed ctop_version of ctop
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: ctop -v | cut -d' ' -f3 | cut -d',' -f1
  register: ctop_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed ctop_version of ctop:"
  ansible.builtin.debug:
    var: ctop_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: ctop_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: ctop_installed_version.stdout != ctop_version
