---
- name: Get latest kubectl_version of kubectl
  ansible.builtin.shell: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt | cut -d'v' -f2
  register: kubectl_version
  changed_when: false

- name: "Latest kubectl_version of kubectl:"
  ansible.builtin.debug:
    var: kubectl_version.stdout

- name: "Set fact with latest kubectl_version of kubectl"
  ansible.builtin.set_fact:
    kubectl_version: "{{ kubectl_version.stdout }}"
