# ➜ kubectl plugin list
# The following compatible plugins are available:
# /home/mikee/.krew/bin/kubectl-krew
# /home/mikee/.krew/bin/kubectl-sniff
---
- name: Upgrade krew
  ansible.builtin.include_tasks: krew/update.yaml
  when: krew_version is not defined

- name: Get installed kubectl_version
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: ~/.krew/bin/kubectl-krew kubectl_version | grep GitTag | awk '{print $2}' | cut -d'v' -f2
  register: kubectl_installed_krew_version
  changed_when: false
  ignore_errors: true

- name: "Installed kubectl_version of krew:"
  ansible.builtin.debug:
    var: kubectl_installed_krew_version.stdout

- name: Include krew/get_latest_version.yaml
  ansible.builtin.include_tasks: krew/get_latest_version.yaml
  when: krew_version is not defined

- name: Include krew/install.yaml
  ansible.builtin.include_tasks: krew/install.yaml
  when: kubectl_installed_krew_version.stdout != krew_version

- name: Import krew/plugins.yaml
  ansible.builtin.import_tasks: krew/plugins.yaml
