---
- name: Get installed kubectl_version
  ansible.builtin.shell: kubectl kubectl_version --short --client=true | grep -i client | cut -d'v' -f2
  register: kubectl_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed kubectl_version of kubectl:"
  ansible.builtin.debug:
    var: kubectl_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: kubectl_version is not defined

- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/{{ architecture_common_name }}/kubectl"
    dest: /usr/local/bin/kubectl
    force: true
    mode: "0755"
  when: kubectl_installed_version.stdout != kubectl_version

- name: Set permissions kubectl
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    mode: "0755"
    owner: root
    group: root

- name: Import krew.yaml
  ansible.builtin.import_tasks: krew.yaml
