---
- name: Get latest version of ollama
  ansible.builtin.shell: curl -Is https://github.com/ollama/ollama/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -d'"' -f1
  register: version
  changed_when: false

- name: "Latest version of ollama:"
  ansible.builtin.debug:
    var: version.stdout

- name: "Set fact with latest version of ollama"
  ansible.builtin.set_fact:
    ollama_version: "{{ version.stdout }}"
