---
- name: Stop container using docker-compose
  ansible.builtin.command: docker-compose stop
  changed_when: frigate_up_result.stderr_lines | length > 1
  register: frigate_up_result
  args:
    chdir: "{{ frigate_install_path }}"

- name: Remove all volumes/containers using docker-compose
  ansible.builtin.command: docker-compose rm -vf
  args:
    chdir: "{{ frigate_install_path }}"

- name: Ensure frigate_install_path dir is removed
  ansible.builtin.file:
    path: "{{ frigate_install_path }}"
    state: absent
