---
- name: Ensure install dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ frigate_install_path }}"

- name: Configure docker-compose file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ frigate_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  loop:
    - docker-compose.yaml

- name: Configure config file
  ansible.builtin.template:
    src: "{{ frigate_templates_path }}/{{ item }}"
    dest: "{{ frigate_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  notify:
    - restart_docker_compose
  loop:
    - config.yaml

# - ansible.builtin.import_tasks: config.yaml

- name: Pull Docker image using docker-compose
  ansible.builtin.command: docker-compose pull
  changed_when: frigate_pull_result.stderr_lines | length > 2
  register: frigate_pull_result
  args:
    chdir: "{{ frigate_install_path }}"

- name: Run using docker-compose
  ansible.builtin.command: docker-compose up -d
  changed_when: frigate_up_result.stderr_lines | length > 2
  register: frigate_up_result
  args:
    chdir: "{{ frigate_install_path }}"
