---
- name: "Create dir for LE cert - {{ letsencrypt_coredns_cert_path }}"
  ansible.builtin.file:
    path: "{{ letsencrypt_coredns_cert_path }}"
    state: directory

- name: Create certificate key
  community.crypto.openssl_privatekey:
    path: "{{ letsencrypt_coredns_cert_key_path }}"
    type: RSA
    size: "{{ letsencrypt_coredns_key_size }}"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ letsencrypt_coredns_cert_csr_path }}"
    privatekey_path: "{{ letsencrypt_coredns_cert_key_path }}"
    common_name: "{{ cert.cn }}"
    subject_alt_name: "{{ item.value | map('regex_replace', '^', 'DNS:') | list }}"
  with_dict:
    cert_sans: "{{ cert.sans | default([]) }}"

- name: Create a challenge using the LE account key file
  community.crypto.acme_certificate:
    account_key_src: "{{ letsencrypt_coredns_account_key_path }}"
    account_email: "{{ letsencrypt_coredns_letsencrypt_email }}"
    src: "{{ letsencrypt_coredns_cert_csr_path }}"
    cert: "{{ letsencrypt_coredns_cert_crt_path }}"
    challenge: dns-01
    force: "{{ letsencrypt_coredns_force_cert_creation }}"
    acme_version: "{{ letsencrypt_coredns_letsencrypt_api_version }}"
    acme_directory: "{{ letsencrypt_coredns_letsencrypt_api }}"
    remaining_days: "{{ letsencrypt_coredns_letsencrypt_days }}"
  register: letsencrypt_coredns_le_challenge

- name: Debug output
  ansible.builtin.debug:
    var: letsencrypt_coredns_le_challenge

- name: Debug output
  ansible.builtin.debug:
    msg: "Certificate is still valid for: {{ letsencrypt_coredns_le_challenge.cert_days }} days"
  when: letsencrypt_coredns_le_challenge.changed == false

- name: Create DNS records
  ansible.builtin.include_tasks: "{{ dns_task_path }}"
  loop: "{{ letsencrypt_coredns_le_challenge.challenge_data | dict2items }}"
  when: letsencrypt_coredns_le_challenge is changed
  vars:
    record_state: present

- name: Reload CoreDNS
  ansible.builtin.shell: docker-compose restart
  args:
    chdir: /opt/coredns
  when: letsencrypt_coredns_le_challenge.changed

- name: Check if DNS records propagated
  ansible.builtin.shell: dig @127.0.0.1 -i txt {{ item.value['dns-01'].record }} | grep -w -- "{{ item.value['dns-01'].resource_value }}"
  loop: "{{ letsencrypt_coredns_le_challenge.challenge_data | dict2items }}"
  retries: 5
  changed_when: false
  until: letsencrypt_coredns_record_check.rc == 0
  register: letsencrypt_coredns_record_check
  when: letsencrypt_coredns_le_challenge.changed

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  community.crypto.acme_certificate:
    account_key_src: "{{ letsencrypt_coredns_account_key_path }}"
    account_email: "{{ letsencrypt_coredns_letsencrypt_email }}"
    acme_directory: "{{ letsencrypt_coredns_letsencrypt_api }}"
    acme_version: "{{ letsencrypt_coredns_letsencrypt_api_version }}"
    remaining_days: "{{ letsencrypt_coredns_letsencrypt_days }}"
    challenge: dns-01
    src: "{{ letsencrypt_coredns_cert_csr_path }}"
    cert: "{{ letsencrypt_coredns_cert_crt_path }}"
    fullchain: "{{ letsencrypt_coredns_cert_fullchain_path }}"
    chain: "{{ letsencrypt_coredns_cert_chain_path }}"
    data: "{{ letsencrypt_coredns_le_challenge }}"
    force: "{{ letsencrypt_coredns_force_cert_creation }}"
    # The following makes sure that if a chain with /CN=DST Root CA X3 in its issuer is provided
    # as an alternative, it will be selected. These are the roots cross-signed by IdenTrust.
    # As long as Let's Encrypt provides alternate chains with the cross-signed root(s) when
    # switching to their own ISRG Root X1 root, this will use the chain ending with a cross-signed
    # root. This chain is more compatible with older TLS clients.
    select_chain:
      - test_certificates: last
        issuer:
          CN: DST Root CA X3
          O: Digital Signature Trust Co.
  when: letsencrypt_coredns_le_challenge.changed

- name: Generate cert pfx pkcs12
  community.crypto.openssl_pkcs12:
    action: export
    friendly_name: cert
    path: "{{ letsencrypt_coredns_cert_pfx_path }}"
    privatekey_path: "{{ letsencrypt_coredns_cert_key_path }}"
    certificate_path: "{{ letsencrypt_coredns_cert_crt_path }}"
    state: present
  when: letsencrypt_coredns_le_challenge.changed

- name: Delete DNS records
  ansible.builtin.include_tasks: "{{ dns_task_path }}"
  loop: "{{ letsencrypt_coredns_le_challenge.challenge_data | dict2items }}"
  when: letsencrypt_coredns_le_challenge.changed
  vars:
    record_state: absent

- name: Reload CoreDNS
  ansible.builtin.shell: docker-compose restart
  args:
    chdir: /opt/coredns
  when: letsencrypt_coredns_le_challenge.changed

# to validate cert: openssl x509 -text -noout -in cert.crt
