---
- name: Set record variables
  ansible.builtin.set_fact:
    letsencrypt_coredns_record_full: "{{ item.value['dns-01'].record }}"
    letsencrypt_coredns_record_without_acme: "{{ item.value['dns-01'].record | regex_replace('_acme-challenge.') }}"
    letsencrypt_coredns_record_without_domain: "{{ item.value['dns-01'].record | regex_replace('.' + domain_name) }}"

# TODO: add caa record
# name: "{{ letsencrypt_coredns_record_without_acme }}"
# content: "0 issue 'letsencrypt.org'"

- name: "Create LE challenge TXT record - {{ record_state ~ ' ' ~ letsencrypt_coredns_record_full }}"
  ansible.builtin.lineinfile:
    path: "/opt/coredns/config/{{ coredns_zone_filename }}"
    regexp: "^{{ letsencrypt_coredns_record_without_domain }}"
    state: "{{ record_state }}"
    line: "{{ letsencrypt_coredns_record_without_domain }} IN TXT {{ item.value['dns-01'].resource_value }}"
