---
# https://docs.ansible.com/ansible/latest/collections/community/crypto/acme_certificate_module.html

- name: Install dependencies
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install pip dependencies
  ansible.builtin.pip:
    name: cryptography
    state: present

- name: Import account_key.yaml
  ansible.builtin.import_tasks: account_key.yaml

- name: "Create dir for letsencrypt_coredns_certs - {{ letsencrypt_coredns_certs_path }}"
  ansible.builtin.file:
    path: "{{ letsencrypt_coredns_certs_path }}"
    state: directory
    mode: "0755"

- name: Generate cert
  ansible.builtin.include_tasks: cert.yaml
  loop: "{{ letsencrypt_coredns_certs }}"
  loop_control:
    loop_var: cert
  vars:
    dns_task_path: dns_coredns.yaml
    domain_name: "{{ cert.domain_name }}"

- name: Create directories for letsencrypt_coredns_certs
  ansible.builtin.file:
    path: "{{ letsencrypt_coredns_certs_path }}/{{ item }}"
    state: directory
    mode: "0755"
  delegate_to: 127.0.0.1
  loop: "{{ letsencrypt_coredns_certs | map(attribute='cn') }}"

- name: Import copy_certs.yaml
  ansible.builtin.import_tasks: copy_certs.yaml
