---
- name: Set hostname fact if IP matches  # noqa: var-naming[no-role-prefix]
  ansible.builtin.set_fact:
    zabbix_hostname: >-
      {{
        (
          (dhcp + static_devices)
          | selectattr('ip', '==', ansible_facts['default_ipv4']['address'])
          | map(attribute='hostname')
          | list
        )[0] if (
          (dhcp + static_devices)
          | selectattr('ip', '==', ansible_facts['default_ipv4']['address'])
          | list
        )|length > 0 else None
      }}


- name: Import zabbix_agent.yaml
  ansible.builtin.import_tasks: zabbix_agent.yaml
- name: Import custom.yaml
  ansible.builtin.import_tasks: custom.yaml
