---
# https://github.com/flyoverhead/ansible-openwrt/blob/main/roles/dhcp/tasks/dhcp.yaml
# https://github.com/gekmihesg/ansible-openwrt/blob/master/library/uci.py

- name: Configure dhcp config
  ansible.builtin.template:
    src: "dhcp.j2"
    dest: "/etc/config/dhcp"
    owner: "root"
    group: "root"
    mode: "0600"
    backup: true
  register: openwrt_setup_dhcp_flag
  # notify:
  #   - reload_dnsmasq

- name: Reload_dnsmasq
  community.general.openwrt_init:
    name: dnsmasq
    state: reloaded
  when:
    - openwrt_setup_dhcp_flag.changed
    - openwrt_setup_openwrt_router_flag or openwrt_setup_openwrt_ap_only_flag
