---
# https://docs.ansible.com/ansible/latest/collections/community/general/openwrt_init_module.html
# https://docs.ansible.com/ansible/latest/collections/community/general/opkg_module.html

- name: Import opkg.yaml
  ansible.builtin.import_tasks: opkg.yaml

- name: Import bpir4.yaml
  ansible.builtin.import_tasks: bpir4.yaml
  when: openwrt_bpir4

- name: Import dhcp.yaml
  ansible.builtin.import_tasks: dhcp.yaml

- name: Import ap.yaml
  ansible.builtin.import_tasks: ap.yaml
  when: not openwrt_router_flag

- name: Import router.yaml
  ansible.builtin.import_tasks: router.yaml
  when: openwrt_router_flag

- name: Import config.yaml
  ansible.builtin.import_tasks: config.yaml

- name: Import zabbix.yaml
  ansible.builtin.import_tasks: zabbix.yaml

# - name: Extract string before dash from hostname
#   ansible.builtin.debug:
#     msg: "{{ inventory_hostname.split('_')[1] }}"
