---
- name: Get latest ollama_version of ollama
  ansible.builtin.shell: curl -Is https://github.com/ollama/ollama/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -d'"' -f1
  register: ollama_version
  changed_when: false

- name: "Latest ollama_version of ollama:"
  ansible.builtin.debug:
    var: ollama_version.stdout

- name: "Set fact with latest ollama_version of ollama"
  ansible.builtin.set_fact:
    ollama_version: "{{ ollama_version.stdout }}"
