---
- name: Get latest dive_version dive
  ansible.builtin.shell: curl -Is https://github.com/wagoodman/dive/releases/latest | grep -i 'location:' | cut -f3 -d'v' | cut -f1 -d'"'
  register: dive_version
  changed_when: false

- name: "Latest dive_version of dive:"
  ansible.builtin.debug:
    var: dive_version.stdout

- name: "Set fact with latest dive_version of dive"
  ansible.builtin.set_fact:
    dive_version: "{{ dive_version.stdout }}"
