---
- name: Get installed dive_version of dive
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: dive dive_version | awk '{print $2}'
  register: dive_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed dive_version of dive:"
  ansible.builtin.debug:
    var: dive_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: dive_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: dive_installed_version.stdout != dive_version
