---
- name: Get latest docker_compose_version docker_compose
  ansible.builtin.shell: curl -Is https://github.com/docker/compose/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -d'"' -f1
  register: docker_compose_version
  changed_when: false

- name: "Latest docker_compose_version of docker_compose:"
  ansible.builtin.debug:
    var: docker_compose_version.stdout

- name: "Set fact with latest docker_compose_version of docker_compose"
  ansible.builtin.set_fact:
    docker_compose_version: "{{ docker_compose_version.stdout }}"
