---
- name: Get latest x11docker_version of x11docker
  ansible.builtin.shell: curl -Is https://github.com/mviereck/x11docker/releases/latest | grep -i 'location:' | cut -f8 -d'/' | cut -f1 -d'"' | cut -d'v' -f2
  register: x11docker_version
  changed_when: false

- name: "Latest x11docker_version of x11docker:"
  ansible.builtin.debug:
    var: x11docker_version.stdout

- name: "Set fact with latest x11docker_version of x11docker"
  ansible.builtin.set_fact:
    x11docker_version: "{{ x11docker_version.stdout }}"
