---
- name: Install dependencies
  ansible.builtin.package:
    name: "xorg-x11-server-Xephyr"
    state: present

- name: Get installed x11docker_version
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: x11docker --x11docker_version
  register: x11docker_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed x11docker_version of x11docker:"
  ansible.builtin.debug:
    var: x11docker_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: x11docker_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: x11docker_installed_version.stdout != x11docker_version
