#!/usr/bin/env bash
# bootstrap_macos_zscaler.sh
#
# Prepares a fresh macOS machine that sits behind a Zscaler SSL-inspecting proxy
# so that CLI tools (mise, pip/pipx, curl, git, node, cargo, ...) trust the
# Zscaler root certificate. Run this once, before `mise install`.
#
# It does two things:
#   1. Exports the Zscaler certificate(s) from the macOS keychains and combines
#      them with the system root certificates into a single PEM bundle at
#      ~/Documents/certs_ca/ca.pem  (the path the Ansible roles already expect).
#   2. Writes a managed block into ~/.zshrc that points the common CLI SSL
#      environment variables at that bundle.
#
# Usage:
#   ./bootstrap_macos_zscaler.sh
#
# The script is idempotent: re-running it refreshes the bundle and the managed
# ~/.zshrc block without creating duplicates.

set -euo pipefail

CERT_DIR="$HOME/Documents/certs_ca"
CERT_BUNDLE="$CERT_DIR/ca.pem"
ZSHRC="$HOME/.zshrc"
BLOCK_START="# >>> zscaler-bootstrap (managed) >>>"
BLOCK_END="# <<< zscaler-bootstrap (managed) <<<"

SYSTEM_KEYCHAIN="/Library/Keychains/System.keychain"
LOGIN_KEYCHAIN="$HOME/Library/Keychains/login.keychain-db"
ROOT_KEYCHAIN="/System/Library/Keychains/SystemRootCertificates.keychain"

log() { printf '\033[1;34m[zscaler-bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[zscaler-bootstrap]\033[0m %s\n' "$*" >&2; }
err() { printf '\033[1;31m[zscaler-bootstrap]\033[0m %s\n' "$*" >&2; }

if [[ "$(uname -s)" != "Darwin" ]]; then
	err "This script is for macOS only. For WSL use grab_zscaler_certs.sh."
	exit 1
fi

# Emit every Zscaler certificate found in the given keychain as PEM.
extract_zscaler_from_keychain() {
	local keychain="$1"
	[[ -r "$keychain" ]] || return 0

	local all_pem
	all_pem="$(security find-certificate -a -p "$keychain" 2>/dev/null || true)"
	[[ -n "$all_pem" ]] || return 0

	# Split the concatenated PEM blob into individual certs (record-separated by
	# 0x1e) and keep only the ones whose subject mentions Zscaler.
	printf '%s\n' "$all_pem" | awk '
		/-----BEGIN CERTIFICATE-----/ { capture=1; cert="" }
		capture { cert = cert $0 "\n" }
		/-----END CERTIFICATE-----/ {
			capture=0
			printf "%s\x1e", cert
		}
	' | while IFS= read -r -d $'\x1e' cert; do
		[[ -n "$cert" ]] || continue
		local subject
		subject="$(printf '%s' "$cert" | openssl x509 -noout -subject 2>/dev/null || true)"
		if printf '%s' "$subject" | grep -qi 'zscaler'; then
			printf '%s' "$cert"
		fi
	done
}

log "Collecting Zscaler certificates from macOS keychains..."

ZSCALER_PEM="$(
	{
		extract_zscaler_from_keychain "$SYSTEM_KEYCHAIN"
		extract_zscaler_from_keychain "$LOGIN_KEYCHAIN"
	} | awk '
		/-----BEGIN CERTIFICATE-----/ { block=""; inblock=1 }
		inblock { block = block $0 "\n" }
		/-----END CERTIFICATE-----/ {
			inblock=0
			if (!seen[block]++) printf "%s", block
		}
	'
)"

if [[ -z "$ZSCALER_PEM" ]]; then
	err "No Zscaler certificate found in the macOS keychains."
	err "Make sure you are connected to the corporate network / Zscaler is active,"
	err "or import the Zscaler root cert into Keychain Access first."
	exit 1
fi

ZSCALER_COUNT="$(grep -c 'BEGIN CERTIFICATE' <<<"$ZSCALER_PEM" || true)"
log "Found $ZSCALER_COUNT Zscaler certificate(s)."

log "Exporting system root certificates..."
SYSTEM_ROOTS_PEM="$(security find-certificate -a -p "$ROOT_KEYCHAIN" 2>/dev/null || true)"
if [[ -z "$SYSTEM_ROOTS_PEM" ]]; then
	warn "Could not read system root certificates; the bundle will contain Zscaler certs only."
fi

log "Writing combined CA bundle to $CERT_BUNDLE"
mkdir -p "$CERT_DIR"
umask 022
{
	printf '# Zscaler certificate(s) (extracted from macOS keychain)\n'
	printf '%s\n' "$ZSCALER_PEM"
	if [[ -n "$SYSTEM_ROOTS_PEM" ]]; then
		printf '# macOS system root certificates\n'
		printf '%s\n' "$SYSTEM_ROOTS_PEM"
	fi
} >"$CERT_BUNDLE"
chmod 0644 "$CERT_BUNDLE"

# Sanity check that the bundle parses.
if ! openssl x509 -in "$CERT_BUNDLE" -noout 2>/dev/null; then
	warn "The generated bundle did not validate cleanly with openssl; please review $CERT_BUNDLE."
fi

log "Updating zsh configuration in $ZSHRC"
touch "$ZSHRC"

read -r -d '' MANAGED_BLOCK <<EOF || true
$BLOCK_START
# Generated by scripts/bootstrap_macos_zscaler.sh - safe to re-run.
# Points common CLI tools at the Zscaler CA bundle so TLS interception works.
export SSL_CERT_FILE="\$HOME/Documents/certs_ca/ca.pem"
export SSL_CERT_DIR=""
export REQUESTS_CA_BUNDLE="\$SSL_CERT_FILE"
export PIP_CERT="\$SSL_CERT_FILE"
export CURL_CA_BUNDLE="\$SSL_CERT_FILE"
export GIT_SSL_CAINFO="\$SSL_CERT_FILE"
export NODE_EXTRA_CA_CERTS="\$SSL_CERT_FILE"
export NPM_CONFIG_CAFILE="\$SSL_CERT_FILE"
export CARGO_HTTP_CAINFO="\$SSL_CERT_FILE"
export AWS_CA_BUNDLE="\$SSL_CERT_FILE"
$BLOCK_END
EOF

# Replace an existing managed block, otherwise append a fresh one.
if grep -qF "$BLOCK_START" "$ZSHRC"; then
	tmp="$(mktemp)"
	awk -v start="$BLOCK_START" -v end="$BLOCK_END" -v block="$MANAGED_BLOCK" '
		$0 == start { inblock=1; print block; next }
		$0 == end { inblock=0; next }
		!inblock { print }
	' "$ZSHRC" >"$tmp"
	mv "$tmp" "$ZSHRC"
	log "Refreshed existing managed block in $ZSHRC"
else
	{
		printf '\n'
		printf '%s\n' "$MANAGED_BLOCK"
	} >>"$ZSHRC"
	log "Appended managed block to $ZSHRC"
fi

log "Done."
log "Open a new terminal (or run: source ~/.zshrc), then run 'mise install'."
