---
- name: Grab information about radio mode (NetworkMode - 3G/LTE, NetworkMBand - GSM/WCDMA band, LTEBand)
  ansible.builtin.uri:
    url: "{{ huawei_lte_huawei_url }}/api/net/net-mode"
    return_content: true
    method: GET
    headers:
      Content-Type: text/xml
      Cookie: "{{ huawei_lte_login_request.cookies_string }}"
  register: huawei_lte_get_net_mode_request
  failed_when: '"<error>" in huawei_lte_get_net_mode_request.content'

- name: Transform huawei_lte_get_net_mode_request from XML to YAML
  ansible.builtin.set_fact:
    huawei_lte_get_net_mode_yaml: "{{ huawei_lte_get_net_mode_request.content | ansible.utils.from_xml }}"

- name: Show huawei_lte_get_net_mode_request response content in YAML
  ansible.builtin.debug:
    var: huawei_lte_get_net_mode_yaml.response
