---
- name: Antidote deps
  ansible.builtin.package:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
      - zsh
      - curl
      - git
      - fzf

- name: "Change user default shell to zsh"
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ antidote_users }}"

- name: Import starship.yaml
  ansible.builtin.import_tasks: starship.yaml
- name: Import plugins.yaml
  ansible.builtin.import_tasks: plugins.yaml
- name: Import work.yaml
  ansible.builtin.import_tasks: work.yaml

- name: Import update.yaml
  ansible.builtin.import_tasks: update.yaml
  tags:
    - update
