---
- name: "ZSH autocomplete"
  become: "{{ (item != user_name) | bool }}"
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~{{ item }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: true
  with_items: "{{ oh_my_zsh_users }}"

- name: "ZSH Syntax Highlighting"
  become: "{{ (item != user_name) | bool }}"
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
    dest: "~{{ item }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: true
  with_items: "{{ oh_my_zsh_users }}"

- name: "Powerlevel10K theme"
  become: "{{ (item != user_name) | bool }}"
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k'
    dest: "~{{ item }}/.oh-my-zsh/custom/themes/powerlevel10k"
    update: true
  with_items: "{{ oh_my_zsh_users }}"

- name: "p10k config"
  ansible.builtin.copy:
    src: templates/p10k.zsh.j2
    dest: "~{{ item }}/.p10k.zsh"
    backup: true
    mode: "0600"
  with_items: "{{ oh_my_zsh_users }}"

- name: Create directory for zsh files
  ansible.builtin.file:
    path: "~{{ item }}/.zsh"
    state: directory
  with_items: "{{ oh_my_zsh_users }}"

- name: zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "~{{ item }}/.zshrc"
    backup: true
    mode: "0600"
  with_items: "{{ oh_my_zsh_users }}"

- name: "zsh configs"
  ansible.builtin.template:
    src: ".zsh/{{ item.1 }}"
    dest: "~{{ item.0 }}/.zsh/{{ item.1 | regex_replace('\\.j2$', '') }}"
    backup: true
    mode: "0600"
  loop: "{{ oh_my_zsh_users | product(lookup('fileglob', 'templates/.zsh/*.j2', wantlist=True) | map('basename') | list) | list }}"

- name: Add folder for fzf key-bindings
  ansible.builtin.file:
    path: "/usr/share/doc/fzf/examples"
    state: directory
  when: ansible_distribution == "Ubuntu"

# Fixing apt-get fzf package
- name: Download fzf key-bindings
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh"
    dest: /usr/share/doc/fzf/examples/key-bindings.zsh
  when: ansible_distribution == "Ubuntu"

- name: "Download zsh-completion"
  become: "{{ (item != user_name) | bool }}"
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions'
    dest: "~{{ item }}/.oh-my-zsh/custom/plugins/zsh-completions"
    update: true
  with_items: "{{ oh_my_zsh_users }}"

- name: "Download fzf-tab-completion"
  become: "{{ (item != user_name) | bool }}"
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/lincheney/fzf-tab-completion.git'
    dest: "~{{ item }}/.oh-my-zsh/custom/plugins/fzf-tab-completion"
    update: true
  with_items: "{{ oh_my_zsh_users }}"

- name: "Download fzf-tab"
  become: "{{ (item != user_name) | bool }}"
  become_user: "{{ item }}"
  ansible.builtin.git:
    repo: 'https://github.com/Aloxaf/fzf-tab'
    dest: "~{{ item }}/.oh-my-zsh/custom/plugins/fzf-tab"
    update: true
  with_items: "{{ oh_my_zsh_users }}"
