---
baremetal_lan_interface: "eth0"  # noqa: var-naming[no-role-prefix]
baremetal_bridge_interface_cidr: "192.168.1.11/24"  # noqa: var-naming[no-role-prefix]
baremetal_bridge_interface_default_gw: "192.168.1.1"  # noqa: var-naming[no-role-prefix]

baremetal_bridge_state: "present"  # noqa: var-naming[no-role-prefix]
# baremetal_bridge_state: "absent"
