---
network_bridge_baremetal_lan_interface: "eth0"
network_bridge_baremetal_bridge_interface_cidr: "192.168.1.11/24"
network_bridge_baremetal_bridge_interface_default_gw: "192.168.1.1"

network_bridge_baremetal_bridge_state: "present"
# baremetal_bridge_state: "absent"
