---
- name: Get latest argocd_version argocd
  ansible.builtin.shell: curl -Is https://github.com/argoproj/argo-cd/releases/latest | grep -i 'location:' | cut -f2 -d'v' | cut -d'"' -f1
  register: argocd_version
  changed_when: false

- name: "Latest argocd_version of argocd:"
  ansible.builtin.debug:
    var: argocd_version.stdout

- name: "Set fact with latest argocd_version of argocd"
  ansible.builtin.set_fact:
    argocd_version: "{{ argocd_version.stdout }}"
