---
- name: Ensure install dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ prometheus_install_path }}"
    - "{{ prometheus_install_path }}/grafana/provisioning/dashboards"
    - "{{ prometheus_install_path }}/grafana/provisioning/datasources"

- name: Configure docker-compose file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ prometheus_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  loop:
    - docker-compose.yaml

- name: Configure config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ prometheus_install_path }}/{{ item }}"
    mode: "0664"
    backup: true
  loop:
    - prometheus.yaml
    - grafana/provisioning/datasources/prometheus.yaml
    - grafana/provisioning/datasources/loki.yaml
    - process-exporter.yaml
    - promtail-config.yaml

- name: Configure dashboards files
  ansible.builtin.copy:
    src: "templates/grafana/provisioning/dashboards/"
    dest: "{{ prometheus_install_path }}/grafana/provisioning/dashboards/"
    mode: "0664"
    backup: true
    # mode :          # copy directories recursively
    # directory_mode:

- name: Pull Docker image using docker-compose
  ansible.builtin.command: docker-compose pull
  changed_when: prometheus_pull_result.stderr_lines | length > 2
  register: prometheus_pull_result
  args:
    chdir: "{{ prometheus_install_path }}"

- name: Run using docker-compose
  ansible.builtin.command: docker-compose up -d
  changed_when: prometheus_up_result.stderr_lines | length > 2
  register: prometheus_up_result
  args:
    chdir: "{{ prometheus_install_path }}"

# - name: Restart using docker-compose
#   ansible.builtin.command: docker-compose restart
#   args:
#     chdir: "{{ prometheus_install_path }}"
