---
- name: Stop Jenkins using docker-compose
  ansible.builtin.command: docker-compose stop
  changed_when: jenkins_up_result.stderr_lines | length > 1
  register: jenkins_up_result
  args:
    chdir: "{{ jenkins_install_path }}"

- name: Remove all Jenkins volumes/containers using docker-compose
  ansible.builtin.command: docker-compose rm -vf
  args:
    chdir: "{{ jenkins_install_path }}"

- name: Ensure jenkins_home dir is removed
  ansible.builtin.file:
    path: "{{ jenkins_home }}"
    state: absent
