---
- name: "Get installed kubescore_version of kubescore"
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.shell: kube-score version --help | awk '{print $3}' | cut -d',' -f1
  register: kubescore_installed_version
  changed_when: false
  ignore_errors: true

- name: "Installed kubescore_version of kubescore:"
  ansible.builtin.debug:
    var: kubescore_installed_version.stdout

- name: Include get_latest_version.yaml
  ansible.builtin.include_tasks: get_latest_version.yaml
  when: kubescore_version is not defined

- name: Include install.yaml
  ansible.builtin.include_tasks: install.yaml
  when: kubescore_installed_version.stdout != kubescore_version
