---
cloud_image_image_path: "/tmp/CentOS-7-x86_64-GenericCloud.qcow2"
cloud_image_kdump_mem: "0M"
cloud_image_centos_qcow2_url: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
cloud_image_image_root_password: "pass123"
cloud_image_base_image_path: "/var/lib/libvirt/images"
