---
- name: Include a playbook for including arch specifc vars
  ansible.builtin.import_playbook: vars.yaml

- name: Fedora bootstrap
  hosts:
    - "{{ hosts_to_deploy | default('localhost') }}"
    # - mikeeClevo
  become: true
  pre_tasks:
    # - ansible.builtin.debug:
    #     var: hostvars[inventory_hostname]
    # https://github.com/geerlingguy/docker-fedora41-ansible/issues/2
    - name: TEMP | Fix due to PAM error in some upstream images
      when: ((ansible_facts['distribution'] == 'Fedora') or (ansible_facts['distribution'] == 'Rocky')) and (ansible_facts['run_in_docker'] is defined)
      # Explicitly don't try to become because that will trigger the broken PAM error
      # become: true
      # Bug in some upstream distros, /etc/shadow has no file perms in container image
      ansible.builtin.file:
        path: /etc/shadow
        mode: "400"
  roles:
    - mikeeq.utils.dnf
    - mikeeq.utils.flatpak
    - mikeeq.apps_desktop.google_chrome
    - mikeeq.apps.docker
    - mikeeq.apps.qemu
    - mikeeq.apps_desktop.terminator
    - mikeeq.apps.vagrant
    - mikeeq.apps.packer
    - mikeeq.machines.gnome
    - mikeeq.apps_desktop.x11docker
    - mikeeq.apps_desktop.vscode
    - mikeeq.apps_desktop.zed
    - mikeeq.machines.fedora
    - mikeeq.apps.mise
    - mikeeq.apps.ollama
    # - mikeeq.apps.nordvpn
    # - mikeeq.apps_desktop.keeweb

- name: Include a playbook for generic-core provisioning
  ansible.builtin.import_playbook: generic-core.yaml

- name: Include a playbook for generic provisioning
  ansible.builtin.import_playbook: generic.yaml
