---
- name: Include a playbook for including arch specifc vars
  ansible.builtin.import_playbook: vars.yaml

- name: Generic Core bootstrap
  hosts: "{{ hosts_to_deploy | default('localhost') }}"
  become: true
  roles:
    - mikeeq.apps.ctop
    - mikeeq.apps.oh_my_zsh
    - mikeeq.apps.dive
    - mikeeq.apps.docker_compose
