---
- name: Include a playbook for including arch specifc vars
  ansible.builtin.import_playbook: vars.yaml

- name: Generic bootstrap
  hosts: "{{ hosts_to_deploy | default('localhost') }}"
  become: true
  roles:
    - mikeeq.utils.pip
    # - mikeeq.apps.keybase
    - mikeeq.apps.kubectl
    - mikeeq.apps.helm
    - mikeeq.apps.stern
    - mikeeq.apps.kail
    - mikeeq.apps.hadolint
    - mikeeq.apps.kubescore
    - mikeeq.apps.istioctl
    - mikeeq.apps.netcore_sdk
    - mikeeq.apps.argocd
    - mikeeq.apps.aws_cli
    - mikeeq.apps.terraform
    - mikeeq.apps.terragrunt
    - mikeeq.apps.terraform_docs
    - mikeeq.apps.tflint
    - mikeeq.apps.trivy
    - mikeeq.apps.azure_functions_core_tools
    - mikeeq.apps.github_cli
    - mikeeq.apps.github_copilot_cli
    - mikeeq.apps.claude_code
