---
- name: Huawei LTE router restart
  hosts: "{{ hosts_to_deploy | default('local') }}"
  become: false
  gather_facts: false
  roles:
    - mikeeq.servers.huawei_lte
  vars:
    huawei_dynamic_task: "restart.yaml"
