---
- name: Fedora host
  hosts: mikeeClevo
  become: true
  pre_tasks:
  # - ansible.builtin.debug:
  #     var: hostvars[inventory_hostname]
  roles:
    - mikeeq.servers.network_static_dns
    - mikeeq.servers.network_bridge
    - mikeeq.servers.libvirt
