---
- name: Include a playbook for including arch specifc vars
  ansible.builtin.import_playbook: vars.yaml

- name: MacOS bootstrap
  hosts:
    - "{{ hosts_to_deploy | default('local') }}"
    # - mikeeClevo
  become: false
  roles:
    # - pkg_mgmt/pip
    - pkg_mgmt/brew
    - apps/oh_my_zsh
    - desktop/macos
    - desktop/apps/vscode
    - desktop/apps/zed
    - apps/claude-code
    - apps/github-copilot-cli
    # - apps/antidote
  vars:
    ansible_remote_tmp: "~{{ user_name }}/.ansible/tmp"
    oh_my_zsh_users:
      - "{{ user_name }}"
    antidote_users:
      - "{{ user_name }}"
