---
- name: Include a playbook for including arch specifc vars
  ansible.builtin.import_playbook: vars.yaml

- name: MacOS bootstrap
  hosts:
    - "{{ hosts_to_deploy | default('localhost') }}"
    # - mikeeClevo
  become: false
  roles:
    # - mikeeq.utils.pip
    - mikeeq.utils.brew
    - mikeeq.apps.oh_my_zsh
    - mikeeq.machines.macos
    - mikeeq.apps_desktop.vscode
    - mikeeq.apps_desktop.zed
    - mikeeq.apps.claude_code
    - mikeeq.apps.github_copilot_cli
    # - mikeeq.apps.antidote
  vars:
    ansible_remote_tmp: "~{{ user_name }}/.ansible/tmp"
    oh_my_zsh_users:
      - "{{ user_name }}"
    antidote_users:
      - "{{ user_name }}"
