---
- name: Bootstrap OpenWRT to enable Ansible
  hosts:
    - openwrt_office
  become: true
  gather_facts: false
  roles:
    - mikeeq.servers.openwrt_bootstrap_ansible

- name: Setup dynamic SQM on OpenWRT
  hosts:
    - openwrt_office
  become: true
  gather_facts: true
  roles:
    - mikeeq.servers.openwrt_dynamic_sqm_lte
