---
# - name: Setup OpenWRT
#   # pre_tasks:
#   #   - ansible.builtin.include_vars: ../
#   hosts:
#     - openwrt
#   become: true
#   gather_facts: true
#   roles:
#     - mikeeq.servers.openwrt_setup

# - name: Provision DNS1
#   hosts:
#     - dns1
#   become: true
#   roles:
#     - mikeeq.apps_server.coredns
#     # - mikeeq.apps_server.letsencrypt_coredns

# - name: Provision DNS2
#   hosts:
#     - dns2
#   become: true
#   roles:
#     - mikeeq.apps_server.adguard_home

- name: Provision DNS1
  hosts:
    - dns1
  become: true
  roles:
    - mikeeq.servers.network_static_dns
    - mikeeq.apps.docker
    - mikeeq.apps_server.coredns
    - mikeeq.apps_server.letsencrypt_coredns

# - name: Provision DNS2
#   hosts:
#     - dns2
#   become: true
#   roles:
#     - mikeeq.servers.network_static_dns
#     - mikeeq.apps.docker
#     - mikeeq.apps_server.adguard_home

- name: Prometheus
  hosts: mikeeClevo
  # hosts: localhost
  become: true
  roles:
    # - mikeeq.apps_server.prometheus
    - mikeeq.apps_server.frigate
    # - mikeeq.apps_server.ollama_docker
    - mikeeq.apps_server.nginx
    - mikeeq.apps_server.immich
    - mikeeq.apps_server.vaultwarden
