---
- name: Include a playbook for including arch specifc vars
  ansible.builtin.import_playbook: vars.yaml

- name: Test playbook
  become: true
  hosts:
    - "{{ hosts_to_deploy | default('local') }}"
    # - mikeeClevo
  roles:
    # - mikeeq.apps_desktop.zed
    # - mikeeq.apps.oh_my_zsh
    - mikeeq.machines.gnome
