---
- name: Zabbix
  hosts: mikeeClevo
  become: true
  roles:
    - mikeeq.apps_server.zabbix

- name: Zabbix agent
  hosts:
    - mikeeClevo
    - mikeePC
    - dns1
    - dns2
  become: true
  roles:
    - mikeeq.apps_server.zabbix_agent
