---
# zed-linux-x86_64.tar.gz / zed-linux-aarch64.tar.gz
- name: Get installed version
  ansible.builtin.shell: ZED_ALLOW_ROOT=true zed --version | cut -d ' ' -f2
  environment:
    ZED_ALLOW_ROOT: true
  register: installed_zed_version
  changed_when: false
  ignore_errors: true

- name: "Installed version of zed:"
  ansible.builtin.debug:
    var: installed_zed_version.stdout

- ansible.builtin.include_tasks: get_latest_version.yaml
  when: zed_version is not defined

- name: Download Zed
  ansible.builtin.get_url:
    url: "https://github.com/zed-industries/zed/releases/download/v{{ zed_version }}/zed-linux-{{ ansible_architecture }}.tar.gz"
    dest: /tmp/zed.tar.gz
  when: installed_zed_version.stdout != zed_version

- name: Create /opt/zed directory
  ansible.builtin.file:
    path: /opt/zed
    state: directory
    mode: "0755"
    owner: root
    group: root
  when: installed_zed_version.stdout != zed_version

- name: Unarchive Zed
  ansible.builtin.unarchive:
    src: /tmp/zed.tar.gz
    dest: /opt/zed
    remote_src: true
    extra_opts:
      - --strip-components=1
  when: installed_zed_version.stdout != zed_version

- name: Symlink zed binary to /usr/local/bin
  ansible.builtin.file:
    src: /opt/zed/bin/zed
    dest: /usr/local/bin/zed
    state: link
  when: installed_zed_version.stdout != zed_version

# - name: Install Zed desktop file
#   ansible.builtin.copy:
#     src: /opt/zed/share/applications/dev.zed.Zed.desktop
#     dest: /usr/share/applications/dev.zed.Zed.desktop
#     remote_src: true
#     mode: "0644"
#   when: installed_zed_version.stdout != zed_version

- name: Copy Zed share files to /usr/share
  ansible.builtin.copy:
    src: /opt/zed/share/
    dest: /usr/share/
    remote_src: true
  # when: installed_zed_version.stdout != zed_version
