---
- ansible.builtin.import_tasks: install.yaml
- ansible.builtin.import_tasks: plugins.yaml
- ansible.builtin.import_tasks: config.yaml

- ansible.builtin.import_tasks: mac.yaml
  when: ansible_os_family == "Darwin"
