---
- name: Copy macbook_pro_2020_hid_apple config
  ansible.builtin.copy:
    src: macbook_pro_2020_hid_apple.conf
    dest: /etc/modprobe.d/macbook_pro_2020_hid_apple.conf
    mode: "0600"
  register: macbook_pro_2020_hid_apple

# sudo modprobe -r hid_apple; sudo modprobe macbook_pro_2020_hid_apple

- name: Rebuild initramfs
  ansible.builtin.shell: dracut -fv
  when: macbook_pro_2020_hid_apple.changed
