---
namespace: mikeeq
name: utils
version: 1.0.0
readme: README.md
authors:
  - mikeeq
description: Package manager helpers and utility roles (dnf, brew, flatpak, pip, snap)
license:
  - GPL-3.0-or-later
repository: https://github.com/mikeeq/ansible-ops-workstation
tags:
  - linux
  - tools
  - infrastructure
dependencies:
  community.general: ">=10.0.0"
build_ignore:
  - molecule
  - "*.tar.gz"
